language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "node"

script:
  - "npm run ci"

git:
  depth: 10

branches:
  only:
    - master

sudo: false

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5

env:
  - CXX=g++-5
