language: node_js
sudo: false

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "node"

before_install:
  - export CXX="g++-4.8" CC="gcc-4.8"
  - curl https://cmake.org/files/v3.6/cmake-3.6.3-Linux-x86_64.tar.gz | tar xz
  - export PATH=${PWD}/cmake-3.6.3-Linux-x86_64/bin:$PATH
  - script/install-emscripten.sh

script:
  - npm run ci

git:
  depth: 10

branches:
  only:
    - master

cache:
  directories:
    - emsdk_portable

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
