language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - "node"

script:
  - "npm run ci"

git:
  depth: 10

branches:
  only:
    - master

sudo: false

env:
  - CXX=clang++

cache:
  directories:
    - emsdk_portable